apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  sources:
    # Helm
    - repoURL: https://kyverno.github.io/kyverno
      chart: kyverno
      targetRevision: 3.6.1
      helm:
        valueFiles:
          - $values/example/development/system/kyverno/values.yaml
    # Values Git repo
    - repoURL: https://github.com/dustjs159/gitops-helm-charts
      targetRevision: master
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true