apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-cronjob
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/dustjs159/gitops-helm-charts
    targetRevision: master
    path: example/development/workloads/cronjob/

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true