apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/dustjs159/gitops-helm-charts
  type: git
  githubAppID: "****"             # Github App의 AppID
  githubAppInstallationID: "****" # Github App의 InstallationID
  githubAppPrivateKey: "****"     # Generate private key 단계에서 다운로드한 private key 경로