apiVersion: v1
kind: Secret
metadata:
  name: argocd-repositories
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/dustjs159/gitops-helm-charts
  type: git
  name: gitops-helm-charts