apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-crds
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno-crds
    targetRevision: 3.6.1

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      selfHeal: true
      prune: false