apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: 3.6.1
      helm:
        releaseName: kyverno
        valueFiles:
          - $values/kyverno/values.yaml
    - repoURL: https://github.com/dustjs159/gitops-helm-charts
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true